# Generated by Django 6.1 on 2026-09-21 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0016_clinicconfiguration_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=255)),
                ('plan', models.CharField(choices=[('free', 'Gratuito'), ('starter', 'Starter'), ('professional', 'Profissional'), ('enterprise', 'Enterprise')], default='free', max_length=32)),
                ('status', models.CharField(choices=[('trialing', 'Em período de teste'), ('active', 'Ativo'), ('past_due', 'Inadimplente'), ('canceled', 'Cancelado'), ('blocked', 'Bloqueado')], default='trialing', max_length=32)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('block_reason', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Assinatura de tenant',
                'verbose_name_plural': 'Assinaturas de tenants',
            },
        ),
        migrations.CreateModel(
            name='TenantUsageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_at', models.DateTimeField(auto_now_add=True)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('storage_mb', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('api_calls', models.PositiveIntegerField(default=0)),
                ('appointments', models.PositiveIntegerField(default=0)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_snapshots', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Snapshot de uso',
                'verbose_name_plural': 'Snapshots de uso',
                'ordering': ['-snapshot_at'],
                'indexes': [models.Index(fields=['clinic', 'snapshot_at'], name='master_pane_clinic__57232d_idx')],
            },
        ),
    ]
