# Generated by Django 6.1 on 2026-09-22 14:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_feature_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aggregate_type', models.CharField(db_index=True, max_length=100)),
                ('aggregate_id', models.UUIDField(db_index=True)),
                ('sequence', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=100)),
                ('event_data', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('actor_id', models.UUIDField()),
                ('tenant_id', models.UUIDField(db_index=True)),
            ],
            options={
                'db_table': 'core_stored_event',
                'ordering': ['aggregate_id', 'sequence'],
                'indexes': [models.Index(fields=['aggregate_type', 'aggregate_id', 'occurred_at'], name='event_aggregate_temporal_idx'), models.Index(fields=['tenant_id', 'aggregate_type', 'occurred_at'], name='event_tenant_temporal_idx')],
                'constraints': [models.UniqueConstraint(fields=('aggregate_type', 'aggregate_id', 'sequence'), name='unique_event_sequence')],
            },
        ),
    ]
