# Generated by Django 6.1 on 2026-10-02 09:15

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0016_clinicconfiguration_icon_and_more'),
        ('people', '0005_professionalprofile_psychiatrist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_label', models.CharField(max_length=80)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('other', 'Outro')], default='other', max_length=16)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('network_hint', models.CharField(blank=True, max_length=16)),
                ('access_digest', models.CharField(max_length=64, unique=True)),
                ('access_expires_at', models.DateTimeField()),
                ('refresh_digest', models.CharField(max_length=64, unique=True)),
                ('previous_refresh_digest', models.CharField(blank=True, db_index=True, max_length=64)),
                ('refresh_expires_at', models.DateTimeField()),
                ('absolute_expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, choices=[('logout', 'Saída pelo paciente'), ('user_revoked', 'Encerrada pelo paciente em outro aparelho'), ('evicted', 'Substituída por um limite de aparelhos'), ('reuse_detected', 'Reuso de credencial de renovação'), ('credentials_changed', 'Senha ou segurança alterada'), ('access_ended', 'Vínculo com a clínica encerrado')], max_length=24)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_sessions', to='clinics.clinic')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_sessions', to='people.patientprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used_at'],
                'base_manager_name': 'infrastructure_objects',
                'indexes': [models.Index(fields=['clinic', 'user', 'revoked_at'], name='mobile_api__clinic__d59d2f_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
