# Generated by Django 6.1 on 2026-10-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mobile_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mobilesession",
            name="revoked_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("logout", "Saída pelo paciente"),
                    ("user_revoked", "Encerrada pelo paciente em outro aparelho"),
                    ("evicted", "Substituída por um limite de aparelhos"),
                    ("reuse_detected", "Reuso de credencial de renovação"),
                    ("credentials_changed", "Senha ou segurança alterada"),
                    ("access_ended", "Vínculo com a clínica encerrado"),
                    ("staff_revoked", "Encerrada pela equipe da clínica"),
                ],
                max_length=24,
            ),
        ),
    ]
