# Generated by Django 6.1 on 2026-09-19 17:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='B2CCBTDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trigger_situation', models.TextField(verbose_name='Situação Desencadeadora')),
                ('automatic_thought', models.TextField(verbose_name='Pensamento Automático')),
                ('cognitive_distortion', models.CharField(max_length=150, verbose_name='Distorção Cognitiva Identificada')),
                ('rational_response', models.TextField(verbose_name='Resposta Racional e Adaptativa')),
                ('emotion_before_percent', models.PositiveSmallIntegerField(default=80)),
                ('emotion_after_percent', models.PositiveSmallIntegerField(default=30)),
            ],
            options={
                'verbose_name': 'Diário de Pensamentos TCC',
                'verbose_name_plural': 'Diários de Pensamentos TCC',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='B2CMindLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(db_index=True, max_length=100)),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mood', models.CharField(choices=[('RADIANT', 'Radiante ✨'), ('CALM', 'Calmo 🌿'), ('EUTHYMIC', 'Estável ⚖️'), ('ANXIOUS', 'Ansioso ⚡'), ('LOW', 'Para Baixo 🌧️')], default='CALM', max_length=20)),
                ('anxiety_score', models.PositiveSmallIntegerField(default=3)),
                ('energy_score', models.PositiveSmallIntegerField(default=4)),
                ('sleep_hours', models.DecimalField(decimal_places=1, default=7.5, max_digits=3)),
                ('emotions_tags', models.JSONField(default=list)),
                ('gratitude_note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Registro de Humor B2C',
                'verbose_name_plural': 'Registros de Humor B2C',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='B2CSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(max_length=100, unique=True)),
                ('plan', models.CharField(choices=[('FREE', 'Gratuito'), ('PLUS_MONTHLY', 'Aurora Mind Plus (Mensal - R$ 29,90)'), ('PLUS_ANNUAL', 'Aurora Mind Plus (Anual - R$ 249,90)')], default='FREE', max_length=30)),
                ('platform', models.CharField(choices=[('APPLE', 'Apple App Store'), ('GOOGLE', 'Google Play Store'), ('DIRECT', 'Assinatura Direta Aurora Elo')], default='APPLE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_until', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Assinatura B2C Aurora Mind',
                'verbose_name_plural': 'Assinaturas B2C Aurora Mind',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid11_code', models.CharField(max_length=20, unique=True, verbose_name='Código CID-11')),
                ('dsm5_code', models.CharField(blank=True, max_length=20, verbose_name='Código DSM-5')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Transtorno')),
                ('category', models.CharField(max_length=120, verbose_name='Categoria Diagnóstica')),
                ('specifiers', models.TextField(blank=True, verbose_name='Especificadores Clínicos')),
            ],
            options={
                'verbose_name': 'Classificação Diagnóstica',
                'verbose_name_plural': 'Classificações Diagnósticas',
                'ordering': ['cid11_code'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=150, verbose_name='Nome do Fármaco (Princípio Ativo)')),
                ('drug_class', models.CharField(max_length=100, verbose_name='Classe Terapêutica')),
                ('dosage', models.CharField(max_length=50, verbose_name='Dosagem (ex: 15mg)')),
                ('posology', models.CharField(max_length=255, verbose_name='Posologia / Horário de Tomada')),
                ('instructions', models.TextField(blank=True, verbose_name='Instruções e Alertas')),
            ],
        ),
        migrations.CreateModel(
            name='PsychiatricPatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('date_of_birth', models.DateField(verbose_name='Data de Nascimento')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone / WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('record_number', models.CharField(max_length=30, unique=True, verbose_name='Número do Prontuário')),
                ('cns', models.CharField(blank=True, max_length=20, verbose_name='Cartão Nacional de Saúde (CNS)')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('status', models.CharField(choices=[('ACTIVE', 'Em Acompanhamento'), ('INPATIENT', 'Internação Ativa'), ('DISCHARGED', 'Alta Terapêutica'), ('TRIAGE', 'Triagem Inicial')], default='ACTIVE', max_length=20, verbose_name='Situação Clínica')),
                ('risk_level', models.CharField(choices=[('LOW', 'Baixo Risco (Ambulatorial Rotineiro)'), ('MODERATE', 'Moderado (Acompanhamento Intensivo)'), ('HIGH', 'Alto Risco / Crise (Alerta SOS)'), ('IMMINENT', 'Risco Iminente de Autoextermínio')], default='LOW', max_length=20, verbose_name='Estratificação de Risco')),
                ('legal_guardian_name', models.CharField(blank=True, max_length=255, verbose_name='Responsável Legal')),
                ('legal_guardian_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone do Responsável')),
                ('known_allergies', models.TextField(blank=True, default='Nenhuma alergia conhecida', verbose_name='Alergias & Reações Adversas')),
                ('medical_comorbidities', models.TextField(blank=True, verbose_name='Comorbidades Clínicas')),
                ('tcle_signed', models.BooleanField(default=True, verbose_name='Termo de Consentimento Assinado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='psychiatry.diagnosticcategory', verbose_name='Diagnóstico Principal CID-11')),
            ],
            options={
                'verbose_name': 'Perfil Psiquiátrico do Paciente',
                'verbose_name_plural': 'Perfis Psiquiátricos dos Pacientes',
            },
        ),
        migrations.CreateModel(
            name='PsychiatricEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(default='Dr. Marcelo Arantes', max_length=255, verbose_name='Médico Psiquiatra')),
                ('doctor_crm', models.CharField(default='CRM/SP 148.920', max_length=30, verbose_name='CRM do Médico')),
                ('evaluation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora da Avaliação')),
                ('modality', models.CharField(choices=[('IN_PERSON', 'Presencial na Clínica'), ('TELEHEALTH', 'Telepsiquiatria HD'), ('HOME_CARE', 'Acompanhamento Domiciliar')], default='IN_PERSON', max_length=20)),
                ('chief_complaint', models.TextField(verbose_name='Queixa Principal')),
                ('hda', models.TextField(verbose_name='História da Doença Atual (HDA)')),
                ('past_psychiatric_history', models.TextField(blank=True, verbose_name='Antecedentes Psiquiátricos')),
                ('family_psychiatric_history', models.TextField(blank=True, verbose_name='Histórico Familiar')),
                ('substance_use_history', models.TextField(blank=True, verbose_name='Uso de Substâncias Psicoativas')),
                ('mse_appearance_attitude', models.CharField(default='Adequada para idade e contexto, colaborativo', max_length=255, verbose_name='Aparência e Atitude')),
                ('mse_psychomotor', models.CharField(default='Normocinético, sem agitação ou acinesia', max_length=255, verbose_name='Psicomotricidade')),
                ('mse_mood_affect', models.CharField(default='Humor eutímico, afeto congruente e modulado', max_length=255, verbose_name='Humor e Afeto')),
                ('mse_speech', models.CharField(default='Fluxo normal, volume e velocidade adequados', max_length=255, verbose_name='Linguagem')),
                ('mse_thought_process', models.CharField(default='Lógico, coerente e orientado a metas', max_length=255, verbose_name='Processo do Pensamento')),
                ('mse_thought_content', models.TextField(default='Sem ideação delirante, delírios ou conteúdo paranoide', verbose_name='Conteúdo do Pensamento')),
                ('mse_perception', models.CharField(default='Sem alucinações auditivas ou visuais no momento', max_length=255, verbose_name='Sensopercepção')),
                ('mse_cognition', models.CharField(default='Orientado auto e alopsiquicamente, memória preservada', max_length=255, verbose_name='Cognição e Orientação')),
                ('mse_insight', models.CharField(default='Crítica e insight preservados sobre o quadro', max_length=255, verbose_name='Crítica e Insight')),
                ('suicidal_ideation_present', models.BooleanField(default=False, verbose_name='Presença de Ideação Suicida')),
                ('suicide_risk_stratification', models.CharField(choices=[('LOW', 'Baixo Risco (Ambulatorial Rotineiro)'), ('MODERATE', 'Moderado (Acompanhamento Intensivo)'), ('HIGH', 'Alto Risco / Crise (Alerta SOS)'), ('IMMINENT', 'Risco Iminente de Autoextermínio')], default='LOW', max_length=20, verbose_name='Risco C-SSRS')),
                ('protective_factors', models.TextField(blank=True, default='Vínculo familiar positivo, adesão ao plano', verbose_name='Fatores de Proteção')),
                ('safety_plan', models.TextField(blank=True, verbose_name='Plano de Segurança para Crises')),
                ('anxiety_analog_scale', models.PositiveSmallIntegerField(default=3, verbose_name='Escala de Ansiedade (0-10)')),
                ('diagnostic_impression', models.TextField(verbose_name='Impressão Diagnóstica')),
                ('therapeutic_plan', models.TextField(verbose_name='Conduta & Plano Terapêutico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='psychiatry.psychiatricpatientprofile', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Avaliação / Anamnese Psiquiátrica',
                'verbose_name_plural': 'Avaliações Psiquiátricas',
                'ordering': ['-evaluation_date'],
            },
        ),
        migrations.CreateModel(
            name='PsychiatricCrisisAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Em Atendimento / Ativo'), ('TRIAGED', 'Triado pela Equipe Médica'), ('DISPATCHED', 'Equipe de Apoio Deslocada'), ('RESOLVED', 'Estabilizado / Encerrado')], default='OPEN', max_length=20)),
                ('responder_notes', models.TextField(blank=True, verbose_name='Conduta de Intervenção Imediata')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crisis_alerts', to='psychiatry.psychiatricpatientprofile')),
            ],
            options={
                'verbose_name': 'Alerta de Crise SOS 24h',
                'verbose_name_plural': 'Alertas de Crise SOS 24h',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationAdherenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('is_taken', models.BooleanField(default=False)),
                ('patient_notes', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychiatry.prescriptionitem')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adherence_logs', to='psychiatry.psychiatricpatientprofile')),
            ],
            options={
                'verbose_name': 'Registro de Adesão Medicamentosa',
                'verbose_name_plural': 'Registros de Adesão Medicamentosa',
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='InpatientBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_code', models.CharField(max_length=20, unique=True, verbose_name='Código do Leito')),
                ('ward', models.CharField(max_length=100, verbose_name='Ala / Enfermaria')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponível'), ('OCCUPIED', 'Ocupado'), ('MAINTENANCE', 'Higienização / Manutenção'), ('RESERVED', 'Reservado para Crise')], default='AVAILABLE', max_length=20)),
                ('admission_type', models.CharField(blank=True, choices=[('VOLUNTARY', 'Internação Voluntária'), ('INVOLUNTARY', 'Internação Involuntária (Lei 10.216/2001)'), ('COMPULSORY', 'Internação Compulsória Judicial')], max_length=20)),
                ('admission_date', models.DateTimeField(blank=True, null=True)),
                ('nursing_notes', models.TextField(blank=True, verbose_name='Notas de Enfermagem Psiquiátrica')),
                ('current_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inpatient_bed', to='psychiatry.psychiatricpatientprofile')),
            ],
            options={
                'verbose_name': 'Leito de Internação',
                'verbose_name_plural': 'Leitos de Internação',
                'ordering': ['bed_code'],
            },
        ),
        migrations.CreateModel(
            name='PsychopharmacologyPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(default='Dr. Marcelo Arantes', max_length=255)),
                ('doctor_crm', models.CharField(default='CRM/SP 148.920', max_length=30)),
                ('recipe_type', models.CharField(choices=[('SIMPLES', 'Receita Simples'), ('CONTROLE_ESPECIAL_C1', 'Controle Especial C1 (Branca em 2 vias)'), ('NOTIFICACAO_B1', 'Notificação de Receita B1 (Azul - Psicotrópicos)'), ('NOTIFICACAO_A', 'Notificação de Receita A (Amarela - Entorpecentes)')], default='CONTROLE_ESPECIAL_C1', max_length=30)),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('expires_date', models.DateField()),
                ('digital_signature_hash', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='psychiatry.psychiatricpatientprofile')),
            ],
            options={
                'verbose_name': 'Prescrição Farmacológica',
                'verbose_name_plural': 'Prescrições Farmacológicas',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='psychiatry.psychopharmacologyprescription'),
        ),
        migrations.CreateModel(
            name='TelepsychiatryRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('doctor_name', models.CharField(default='Dr. Marcelo Arantes', max_length=255)),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendada'), ('IN_PROGRESS', 'Em Andamento (HD E2EE)'), ('COMPLETED', 'Concluída'), ('CANCELLED', 'Cancelada')], default='SCHEDULED', max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('session_notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tele_sessions', to='psychiatry.psychiatricpatientprofile')),
            ],
            options={
                'verbose_name': 'Sala de Telepsiquiatria',
                'verbose_name_plural': 'Salas de Telepsiquiatria',
                'ordering': ['-scheduled_for'],
            },
        ),
    ]
