# Generated by Django 6.1 on 2026-09-19 18:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychiatry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddictionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GAMBLING', 'Transtorno do Jogo / Ludopatia (Bets & Cassinos)'), ('ALCOHOL', 'Dependência Alcoólica (Alcoolismo)'), ('CHEMICAL', 'Dependência Química (Cocaína, Crack, Opioides, Estimulantes)'), ('POLYADDICTION', 'Polidependência / Adicção Cruzada')], default='GAMBLING', max_length=30, verbose_name='Categoria Aditiva Principal')),
                ('severity', models.CharField(choices=[('MILD', 'Leve (Ambulatorial Inicial)'), ('MODERATE', 'Moderada (Acompanhamento Intensivo)'), ('SEVERE', 'Grave (Indicação de Internação / Desintoxicação)'), ('CRITICAL', 'Crítica (Risco Iminente / Fissura Incontrolável)')], default='MODERATE', max_length=20, verbose_name='Gravidade Clínica')),
                ('gambling_modalities', models.JSONField(blank=True, default=list, verbose_name='Modalidades de Aposta (Bets Esportivas, Slots, Tigrinho, Pôquer, Roleta)')),
                ('estimated_financial_debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Dívida Financeira Acumulada em R$')),
                ('chasing_losses', models.BooleanField(default=True, verbose_name='Comportamento de Correr Atrás do Prejuízo (Chasing)')),
                ('pgsi_score', models.PositiveSmallIntegerField(default=0, verbose_name='Escore PGSI (Problem Gambling Severity Index: 0-27)')),
                ('primary_substance', models.CharField(blank=True, max_length=100, verbose_name='Substância Psicoativa Principal')),
                ('secondary_substances', models.JSONField(blank=True, default=list, verbose_name='Substâncias Secundárias')),
                ('audit_score', models.PositiveSmallIntegerField(default=0, verbose_name='Escore AUDIT (Álcool: 0-40)')),
                ('dast_score', models.PositiveSmallIntegerField(default=0, verbose_name='Escore DAST-10 (Drogas: 0-10)')),
                ('ciwa_score', models.PositiveSmallIntegerField(default=0, verbose_name='Escore CIWA-Ar (Abstinência Alcoólica: 0-67)')),
                ('sobriety_since', models.DateField(blank=True, null=True, verbose_name='Data de Início da Sobriedade Atual (Clean Time)')),
                ('longest_sobriety_days', models.PositiveIntegerField(default=0, verbose_name='Recorde de Dias Limpos')),
                ('relapse_count', models.PositiveIntegerField(default=0, verbose_name='Número de Recaídas Pregressas')),
                ('sponsor_name', models.CharField(blank=True, max_length=150, verbose_name='Nome do Padrinho/Madrinha dos 12 Passos')),
                ('sponsor_phone', models.CharField(blank=True, max_length=25, verbose_name='Telefone de Apoio do Padrinho')),
                ('fellowship_group', models.CharField(blank=True, default='A.A. / N.A. / J.A.', max_length=120, verbose_name='Irmandade de Mútuo Apoio Frequentada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addiction_profile', to='psychiatry.psychiatricpatientprofile', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Perfil de Adictologia (Apostas, Álcool e Drogas)',
                'verbose_name_plural': 'Perfis de Adictologia',
            },
        ),
        migrations.CreateModel(
            name='CravingTrackingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('craving_intensity', models.PositiveSmallIntegerField(default=5, verbose_name='Intensidade da Fissura (0 a 10)')),
                ('target_urge', models.CharField(max_length=80, verbose_name='Objeto da Fissura (ex: Bet/Cassino, Cerveja, Cocaína)')),
                ('trigger_detail', models.TextField(blank=True, verbose_name='Gatilho Desencadeante')),
                ('halt_factors', models.JSONField(blank=True, default=list, verbose_name='Fatores HALT Ativos (Hungry, Angry, Lonely, Tired)')),
                ('coping_technique', models.CharField(blank=True, max_length=150, verbose_name='Técnica de Enfrentamento Utilizada')),
                ('urge_surfed_successfully', models.BooleanField(default=True, verbose_name='Fissura Superada sem Recaída (Urge Surfing)')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='craving_logs', to='psychiatry.psychiatricpatientprofile', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Registro de Fissura / Craving',
                'verbose_name_plural': 'Registros de Fissura / Craving',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TwelveStepsAnamnesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_steps_count', models.PositiveSmallIntegerField(default=1, verbose_name='Passos Concluídos (1-12)')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho no Redis (Em Preenchimento)'), ('IN_PROGRESS', 'Em Análise pela Equipe Multidisciplinar'), ('CONSOLIDATED', 'Consolidada com Plano de Prevenção de Recaída')], default='DRAFT', max_length=20)),
                ('step1_powerlessness', models.TextField(blank=True, verbose_name='Passo 1: Reconhecimento da impotência e ingovernabilidade da vida')),
                ('step2_restoration_hope', models.TextField(blank=True, verbose_name='Passo 2: Crença na restauração da sanidade e equilíbrio')),
                ('step3_surrender_care', models.TextField(blank=True, verbose_name='Passo 3: Decisão de entregar o controle ao cuidado terapêutico')),
                ('step4_moral_inventory', models.TextField(blank=True, verbose_name='Passo 4: Inventário moral, financeiro, culpas e segredos')),
                ('step5_confession_admission', models.TextField(blank=True, verbose_name='Passo 5: Admissão da natureza exata dos erros e padrões aditivos')),
                ('step6_readiness', models.TextField(blank=True, verbose_name='Passo 6: Prontidão para transformar defeitos de caráter e impulsividade')),
                ('step7_humility', models.TextField(blank=True, verbose_name='Passo 7: Superação humilde das próprias fraquezas e limitações')),
                ('step8_amends_list', models.TextField(blank=True, verbose_name='Passo 8: Lista de familiares, credores e pessoas prejudicadas')),
                ('step9_reparations_plan', models.TextField(blank=True, verbose_name='Passo 9: Plano de reparação direta, solvência e reconciliação')),
                ('step10_daily_inventory', models.TextField(blank=True, verbose_name='Passo 10: Vigilância diária e admissão imediata de deslizes')),
                ('step11_mindfulness_prayer', models.TextField(blank=True, verbose_name='Passo 11: Práticas meditativas, conexão interior e serenidade')),
                ('step12_service_purpose', models.TextField(blank=True, verbose_name='Passo 12: Despertar terapêutico e transmissão da mensagem de sobriedade')),
                ('relapse_triggers', models.JSONField(blank=True, default=list, verbose_name='Gatilhos Críticos de Recaída Identificados (HALT)')),
                ('relapse_risk_index', models.PositiveSmallIntegerField(default=50, verbose_name='Índice de Risco de Recaída (0-100)')),
                ('ai_prevention_plan', models.TextField(blank=True, verbose_name='Plano Individual de Prevenção de Recaída (Gerado por IA)')),
                ('doctor_conclusions', models.TextField(blank=True, verbose_name='Parecer do Médico Psiquiatra Especialista')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twelve_steps_records', to='psychiatry.psychiatricpatientprofile', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Anamnese Psiquiátrica dos 12 Passos',
                'verbose_name_plural': 'Anamneses dos 12 Passos',
                'ordering': ['-session_date'],
            },
        ),
    ]
