# Generated by Django 6.1 on 2026-09-20 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0016_clinicconfiguration_icon_and_more'),
        ('psychiatry', '0002_addictionprofile_cravingtrackinglog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='b2ccbtdiary',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='b2ccbtdiary_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='b2cmindlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='b2cmindlog_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='b2csubscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='b2csubscription_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inpatientbed',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='psychiatric_beds', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='psychiatricevaluation',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='psychiatric_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='psychiatricpatientprofile',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='psychiatric_profiles', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='psychiatricpatientprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='psychiatric_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='twelvestepsanamnesis',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='psychiatric_step_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='twelvestepsanamnesis',
            name='draft_steps',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='psychiatricpatientprofile',
            name='tcle_signed',
            field=models.BooleanField(default=False, verbose_name='Termo de Consentimento Assinado'),
        ),
        migrations.AlterField(
            model_name='twelvestepsanamnesis',
            name='relapse_risk_index',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Índice de Risco de Recaída (0-100)'),
        ),
    ]
