# Generated by Django 6.1 on 2026-10-02 08:42

import concierge.fields
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0016_clinicconfiguration_icon_and_more'),
        ('people', '0005_professionalprofile_psychiatrist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_rules', to='clinics.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_rules_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version', '-created_at'],
                'base_manager_name': 'infrastructure_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationRuleStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('call', 'Ligação'), ('visit', 'Visita presencial')], max_length=16)),
                ('day_after_discharge', models.PositiveSmallIntegerField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('responsible_role', models.CharField(choices=[('administrative_staff', 'Equipe administrativa (concierge)'), ('therapist', 'Terapeuta'), ('clinic_admin', 'Administrador da clínica')], default='administrative_staff', max_length=32)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_rule_steps', to='clinics.clinic')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='concierge.communicationrule')),
            ],
            options={
                'ordering': ['day_after_discharge', 'order', 'kind'],
                'base_manager_name': 'infrastructure_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discharge_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Em acompanhamento'), ('completed', 'Acompanhamento concluído'), ('canceled', 'Cancelada')], default='active', max_length=16)),
                ('rule_snapshot', models.JSONField(blank=True, default=dict)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharges_canceled', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharges', to='clinics.clinic')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharges', to='people.patientprofile')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharges_registered', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharges', to='concierge.communicationrule')),
            ],
            options={
                'ordering': ['-discharge_date', '-created_at'],
                'base_manager_name': 'infrastructure_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AftercareContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('call', 'Ligação'), ('visit', 'Visita presencial')], max_length=16)),
                ('day_after_discharge', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField()),
                ('original_due_date', models.DateField()),
                ('reschedule_count', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Agendado'), ('done', 'Realizado'), ('missed', 'Não realizado'), ('canceled', 'Cancelado')], default='scheduled', max_length=16)),
                ('responsible_role', models.CharField(choices=[('administrative_staff', 'Equipe administrativa (concierge)'), ('therapist', 'Terapeuta'), ('clinic_admin', 'Administrador da clínica')], default='administrative_staff', max_length=32)),
                ('outcome', models.CharField(blank=True, choices=[('reached', 'Conseguiu falar'), ('no_answer', 'Não atendeu'), ('declined', 'Recusou o contato'), ('visit_done', 'Visita realizada'), ('visit_not_possible', 'Visita não foi possível')], default='', max_length=24)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', concierge.fields.EncryptedTextField(blank=True, default='')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aftercare_contacts', to='clinics.clinic')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aftercare_contacts_completed', to=settings.AUTH_USER_MODEL)),
                ('discharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='concierge.discharge')),
            ],
            options={
                'ordering': ['due_date', 'kind', 'day_after_discharge'],
                'base_manager_name': 'infrastructure_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FamilyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=100)),
                ('phone', concierge.fields.EncryptedTextField(blank=True, default='')),
                ('email', concierge.fields.EncryptedTextField(blank=True, default='')),
                ('is_primary', models.BooleanField(default=False)),
                ('consent_to_contact', models.BooleanField(default=False)),
                ('consent_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('consent_note', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_contacts', to='clinics.clinic')),
                ('consent_recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_consents_recorded', to=settings.AUTH_USER_MODEL)),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_contacts', to='people.patientprofile')),
            ],
            options={
                'ordering': ['-is_primary', 'full_name'],
                'base_manager_name': 'infrastructure_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FamilyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('call_me', 'Que me liguem'), ('visit_me', 'Que me visitem'), ('bring_item', 'Que tragam algo'), ('message', 'Que recebam um recado')], max_length=16)),
                ('description', concierge.fields.EncryptedTextField()),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('forwarded', 'Encaminhado à família'), ('fulfilled', 'Atendido'), ('declined', 'Não atendido'), ('canceled', 'Cancelado')], default='open', max_length=16)),
                ('requested_at', models.DateTimeField()),
                ('forwarded_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=500)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_requests', to='clinics.clinic')),
                ('family_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='concierge.familycontact')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_requests', to='people.patientprofile')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_requests_recorded', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_requests_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'base_manager_name': 'infrastructure_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ConciergeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('call', 'Ligação'), ('visit', 'Visita'), ('message', 'Mensagem'), ('email', 'E-mail')], max_length=16)),
                ('direction', models.CharField(choices=[('outbound', 'Da clínica para a família'), ('inbound', 'Da família para a clínica')], default='outbound', max_length=16)),
                ('occurred_at', models.DateTimeField()),
                ('summary', concierge.fields.EncryptedTextField()),
                ('aftercare_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='concierge.aftercarecontact')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concierge_logs', to='clinics.clinic')),
                ('corrects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='concierge.conciergelog')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concierge_logs', to='people.patientprofile')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concierge_logs_recorded', to=settings.AUTH_USER_MODEL)),
                ('family_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='concierge.familycontact')),
                ('family_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='concierge.familyrequest')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
                'base_manager_name': 'infrastructure_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='communicationrule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('clinic',), name='unique_active_communication_rule_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='communicationrule',
            constraint=models.UniqueConstraint(fields=('clinic', 'version'), name='unique_rule_version_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='communicationrulestep',
            constraint=models.UniqueConstraint(fields=('rule', 'kind', 'day_after_discharge'), name='unique_step_per_rule_kind_day'),
        ),
        migrations.AddConstraint(
            model_name='communicationrulestep',
            constraint=models.CheckConstraint(condition=models.Q(('day_after_discharge__gte', 1), ('day_after_discharge__lte', 365)), name='rule_step_day_between_1_and_365'),
        ),
        migrations.AddIndex(
            model_name='discharge',
            index=models.Index(fields=['clinic', 'status', 'discharge_date'], name='concierge_d_clinic__e5635e_idx'),
        ),
        migrations.AddConstraint(
            model_name='discharge',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('clinic', 'patient_profile'), name='unique_active_discharge_per_patient'),
        ),
        migrations.AddIndex(
            model_name='aftercarecontact',
            index=models.Index(fields=['clinic', 'status', 'due_date'], name='concierge_a_clinic__0b4da3_idx'),
        ),
        migrations.AddConstraint(
            model_name='aftercarecontact',
            constraint=models.UniqueConstraint(fields=('discharge', 'kind', 'day_after_discharge'), name='unique_contact_per_discharge_kind_day'),
        ),
        migrations.AddIndex(
            model_name='familycontact',
            index=models.Index(fields=['clinic', 'patient_profile', 'is_active'], name='concierge_f_clinic__fae352_idx'),
        ),
        migrations.AddIndex(
            model_name='familyrequest',
            index=models.Index(fields=['clinic', 'status', 'requested_at'], name='concierge_f_clinic__012ef7_idx'),
        ),
        migrations.AddIndex(
            model_name='conciergelog',
            index=models.Index(fields=['clinic', 'patient_profile', 'occurred_at'], name='concierge_c_clinic__6ca84e_idx'),
        ),
    ]
