# Generated by Django 6.1 on 2026-09-11 05:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_user_preferred_language"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mfarecoverycode",
            name="unique_mfa_recovery_code_per_user",
        ),
        migrations.RemoveField(
            model_name="mfarecoverycode",
            name="user",
        ),
        migrations.DeleteModel(
            name="UserMFA",
        ),
        migrations.DeleteModel(
            name="MFARecoveryCode",
        ),
    ]
