# Generated by Django 6.1 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_remove_mfa"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicinvitation",
            name="initial_category",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="clinicinvitation",
            name="unit_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="clinicinvitation",
            name="valid_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clinicinvitation",
            name="valid_until",
            field=models.DateField(blank=True, null=True),
        ),
    ]
