# Generated by Django 6.1 on 2026-10-03 02:37

import accounts.cpf
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[accounts.cpf.validate_cpf], verbose_name='CPF'),
        ),
    ]
