# Generated by Django 6.1 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0004_review_governance_wave"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professionalprofile",
            name="category",
            field=models.CharField(
                choices=[
                    ("psychologist", "Psicologia"),
                    ("psychiatrist", "Psiquiatria"),
                    ("therapist", "Terapia"),
                    ("other", "Outra categoria"),
                ],
                max_length=32,
            ),
        ),
    ]
